// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Srudent.proto

package com.demo.netty.grpc.generate;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.demo.netty.grpc.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realname = 2;</code>
   */
  java.lang.String getRealname();
  /**
   * <code>string realname = 2;</code>
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
