// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Srudent.proto

package com.demo.netty.grpc.generate;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.demo.netty.grpc.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
