// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Srudent.proto

package com.demo.netty.grpc.generate;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.demo.netty.grpc.StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_info = 1;</code>
   */
  java.lang.String getRequestInfo();
  /**
   * <code>string request_info = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestInfoBytes();
}
