// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Srudent.proto

package com.demo.netty.grpc.generate;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.demo.netty.grpc.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response_info = 1;</code>
   */
  java.lang.String getResponseInfo();
  /**
   * <code>string response_info = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseInfoBytes();
}
