// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Srudent.proto

package com.demo.netty.grpc.generate;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.demo.netty.grpc.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.demo.netty.grpc.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<com.demo.netty.grpc.generate.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .com.demo.netty.grpc.StudentResponse studentResponse = 1;</code>
   */
  com.demo.netty.grpc.generate.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .com.demo.netty.grpc.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .com.demo.netty.grpc.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.demo.netty.grpc.generate.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .com.demo.netty.grpc.StudentResponse studentResponse = 1;</code>
   */
  com.demo.netty.grpc.generate.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
