// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Srudent.proto

package com.demo.netty.grpc.generate;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_netty_grpc_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_netty_grpc_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_netty_grpc_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_netty_grpc_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_netty_grpc_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_netty_grpc_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_netty_grpc_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_netty_grpc_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_netty_grpc_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_netty_grpc_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_netty_grpc_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_netty_grpc_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_netty_grpc_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_netty_grpc_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rSrudent.proto\022\023com.demo.netty.grpc\"\035\n\t" +
      "MyRequest\022\020\n\010username\030\001 \001(\t\"\036\n\nMyRespons" +
      "e\022\020\n\010realname\030\002 \001(\t\"\035\n\016StudentRequest\022\013\n" +
      "\003age\030\001 \001(\005\":\n\017StudentResponse\022\014\n\004name\030\001 " +
      "\001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"T\n\023Studen" +
      "tResponseList\022=\n\017studentResponse\030\001 \003(\0132$" +
      ".com.demo.netty.grpc.StudentResponse\"%\n\r" +
      "StreamRequest\022\024\n\014request_info\030\001 \001(\t\"\'\n\016S" +
      "treamResponse\022\025\n\rresponse_info\030\001 \001(\t2\254\002\n" +
      "\016StudentService\022X\n\025GetRealNameByUsername" +
      "\022\036.com.demo.netty.grpc.MyRequest\032\037.com.d" +
      "emo.netty.grpc.MyResponse\022i\n\026GetStudentW" +
      "rapperByAge\022#.com.demo.netty.grpc.Studen" +
      "tRequest\032(.com.demo.netty.grpc.StudentRe" +
      "sponseList(\001\022U\n\006BiTalk\022\".com.demo.netty." +
      "grpc.StreamRequest\032#.com.demo.netty.grpc" +
      ".StreamResponse(\0010\001B.\n\034com.demo.netty.gr" +
      "pc.generateB\014StudentProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_demo_netty_grpc_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_demo_netty_grpc_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_netty_grpc_MyRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_com_demo_netty_grpc_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_demo_netty_grpc_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_netty_grpc_MyResponse_descriptor,
        new java.lang.String[] { "Realname", });
    internal_static_com_demo_netty_grpc_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_demo_netty_grpc_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_netty_grpc_StudentRequest_descriptor,
        new java.lang.String[] { "Age", });
    internal_static_com_demo_netty_grpc_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_demo_netty_grpc_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_netty_grpc_StudentResponse_descriptor,
        new java.lang.String[] { "Name", "Age", "City", });
    internal_static_com_demo_netty_grpc_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_demo_netty_grpc_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_netty_grpc_StudentResponseList_descriptor,
        new java.lang.String[] { "StudentResponse", });
    internal_static_com_demo_netty_grpc_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_demo_netty_grpc_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_netty_grpc_StreamRequest_descriptor,
        new java.lang.String[] { "RequestInfo", });
    internal_static_com_demo_netty_grpc_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_demo_netty_grpc_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_netty_grpc_StreamResponse_descriptor,
        new java.lang.String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
